import { Injectable } from '@nestjs/common';
import { homedir } from 'os';
import { join } from 'path';
import { mkdir, writeFile, rename, unlink, chmod } from 'fs/promises';
import { randomBytes } from 'crypto';
import { createLogger } from '../../../common/logging/logger';

const logger = createLogger('CopilotHooksConfigService');

const CONFIG_FILE_MODE = 0o600;
const SCRIPT_FILE_MODE = 0o755;
const HOOK_TIMEOUT_SEC = 10;

/**
 * Structural contract for a per-provider hook-config installer. Both the Claude
 * `HooksConfigService` and this Copilot installer satisfy it (Claude WITHOUT any
 * source change — structural typing only), so the launch pipeline can dispatch on
 * adapter identity instead of a hardcoded provider string.
 */
export interface HookConfigInstaller {
  ensureHooksConfig(projectRootPath: string): Promise<void>;
}

/**
 * Copilot lifecycle relay, materialized to `~/.copilot/hooks/devchain-relay.sh`.
 *
 * Copilot's config surface differs from Claude on all three axes (P3-S1 spike):
 *  - the hook event name is passed as `$1` ("SessionStart" | "Stop"), and the
 *    provider payload arrives on stdin as snake_case Claude-shaped JSON;
 *  - this relay normalizes that payload into DevChain's provider-neutral hook DTO
 *    (`providerName:"copilot"` + `providerSessionId`, see P3-2 hook-event.dto.ts).
 *
 * BLAST-RADIUS GUARD (critical): the config lives at the USER level
 * (`~/.copilot/hooks/devchain.json`), so copilot runs this relay for EVERY copilot
 * session on the machine — not just devchain-launched ones. The first statements
 * make it a hard no-op (exit 0, no read, no POST) for any session that lacks the
 * `DEVCHAIN_*` env the session launcher injects. Fail-open everywhere: copilot is
 * never blocked by a relay error.
 *
 * Soft-requires jq + curl (standard on dev machines): both are guarded up front
 * with `command -v … || exit 0`, and every payload-extraction jq read is
 * `|| exit 0`, so a missing tool or malformed hook JSON no-ops instead of dying
 * under `set -euo pipefail`.
 */
const RELAY_SCRIPT_CONTENT = `#!/bin/bash
# DevChain Copilot relay — bridges GitHub Copilot CLI lifecycle hooks to DevChain.
# Auto-generated by DevChain. Do not edit manually.
# Requires: jq, curl

set -euo pipefail

# ── Blast-radius guard ───────────────────────────────────────────────────────
# This config is USER-LEVEL, so copilot runs it for EVERY copilot session. Exit
# instantly (no read, no POST) unless this is a devchain-launched session.
if [ -z "\${DEVCHAIN_API_URL:-}" ]; then exit 0; fi
if [ -z "\${DEVCHAIN_SESSION_ID:-}" ]; then exit 0; fi

# ── Tooling guard (fail-open) ────────────────────────────────────────────────
# The relay must NEVER block copilot: if jq/curl are missing, no-op (exit 0)
# instead of dying under set -euo pipefail.
command -v jq >/dev/null 2>&1 || exit 0
command -v curl >/dev/null 2>&1 || exit 0

# The hook event name is supplied as the first arg by devchain.json.
HOOK_EVENT_NAME="\${1:-}"
case "$HOOK_EVENT_NAME" in
  SessionStart|Stop) ;;
  *) exit 0 ;;
esac

INPUT="$(cat)" || exit 0

# tmux session name (prefer the injected value; fall back to a live query).
TMUX_SESSION="\${DEVCHAIN_TMUX_SESSION_NAME:-}"
if [ -z "$TMUX_SESSION" ] && command -v tmux >/dev/null 2>&1; then
  TMUX_SESSION="$(tmux display-message -p '#S' 2>/dev/null || true)"
fi
if [ -z "$TMUX_SESSION" ]; then exit 0; fi

# ── Provider-payload extraction (fail-open) ──────────────────────────────────
# EVERY jq read is guarded with "|| exit 0": malformed hook JSON (or any jq
# hiccup) no-ops silently — it must never crash under set -euo pipefail, and must
# never POST partial data. Fields are extracted ONCE here, then handed to the
# builder below as plain --arg values (no nested command substitution).
SESSION_ID="$(echo "$INPUT" | jq -r '.session_id // empty')" || exit 0
MODEL="$(echo "$INPUT" | jq -r '.model // empty')" || exit 0
TRANSCRIPT_PATH="$(echo "$INPUT" | jq -r '.transcript_path // empty')" || exit 0

# 'source' belongs ONLY to SessionStart (DTO is .strict()). It is required there,
# so default to "startup" — a lifecycle confirmation must never be dropped on a
# technicality (copilot does send a source; this is just a safety net).
SOURCE=""
if [ "$HOOK_EVENT_NAME" = "SessionStart" ]; then
  SOURCE="$(echo "$INPUT" | jq -r '.source // empty')" || exit 0
  if [ -z "$SOURCE" ]; then SOURCE="startup"; fi
fi

# 'stopReason' belongs ONLY to Stop (kept off SessionStart to stay strict-clean).
STOP_REASON=""
if [ "$HOOK_EVENT_NAME" = "Stop" ]; then
  STOP_REASON="$(echo "$INPUT" | jq -r '.stop_reason // empty')" || exit 0
fi

# Normalize copilot's snake_case payload into DevChain's hook-event shape.
# providerName=copilot + providerSessionId (from session_id) select the
# provider-neutral ingestion path; sessionId/projectId/agentId come from the
# injected DEVCHAIN_* env. Each optional key is added conditionally so both the
# SessionStart and Stop .strict() variants stay clean.
PAYLOAD="$(jq -n \\
  --arg hookEventName "$HOOK_EVENT_NAME" \\
  --arg providerName "copilot" \\
  --arg providerSessionId "$SESSION_ID" \\
  --arg source "$SOURCE" \\
  --arg model "$MODEL" \\
  --arg transcriptPath "$TRANSCRIPT_PATH" \\
  --arg stopReason "$STOP_REASON" \\
  --arg tmuxSessionName "$TMUX_SESSION" \\
  --arg projectId "\${DEVCHAIN_PROJECT_ID:-}" \\
  --arg agentId "\${DEVCHAIN_AGENT_ID:-}" \\
  --arg sessionId "\${DEVCHAIN_SESSION_ID:-}" \\
  '{
    hookEventName: \$hookEventName,
    providerName: \$providerName,
    tmuxSessionName: \$tmuxSessionName,
    projectId: \$projectId,
    agentId: (if \$agentId == "" then null else \$agentId end),
    sessionId: (if \$sessionId == "" then null else \$sessionId end)
  }
  + (if \$providerSessionId != "" then {providerSessionId: \$providerSessionId} else {} end)
  + (if \$source != "" then {source: \$source} else {} end)
  + (if \$model != "" then {model: \$model} else {} end)
  + (if \$transcriptPath != "" then {transcriptPath: \$transcriptPath} else {} end)
  + (if \$stopReason != "" then {stopReason: \$stopReason} else {} end)
  ')" || exit 0

# Fire-and-forget POST. Fail-open: any curl error exits 0 so copilot never blocks.
curl -s -f -X POST \\
  -H "Content-Type: application/json" \\
  -d "$PAYLOAD" \\
  "\${DEVCHAIN_API_URL}/api/hooks/events" \\
  --max-time 10 \\
  >/dev/null 2>&1 || exit 0

exit 0
`;

/**
 * CopilotHooksConfigService — Copilot's parallel to the Claude `HooksConfigService`.
 *
 * Writes a copilot-shaped hook config + relay at the USER level (per P3-S1):
 *  - `~/.copilot/hooks/devchain-relay.sh`  (the normalizing bash relay, chmod +x)
 *  - `~/.copilot/hooks/devchain.json`      (copilot hook config, `version:1`)
 *
 * Copilot's config schema differs from Claude's `settings.local.json`: the command
 * field is **`bash`** (not `command`), the timeout key is **`timeoutSec`**, event
 * keys are registered PascalCase (`SessionStart`/`Stop`), and the file is a JSON
 * document dedicated to devchain — so it is written wholesale (no user-key merge,
 * unlike Claude's shared settings file).
 *
 * The Claude installer is left byte-for-byte untouched; this is a parallel service,
 * not a refactor of the Claude path.
 */
@Injectable()
export class CopilotHooksConfigService implements HookConfigInstaller {
  /** Stable provider identity used by the launch pipeline to select this installer. */
  readonly providerName = 'copilot';

  private get hooksDir(): string {
    return join(homedir(), '.copilot', 'hooks');
  }

  private get relayScriptPath(): string {
    return join(this.hooksDir, 'devchain-relay.sh');
  }

  private get configPath(): string {
    return join(this.hooksDir, 'devchain.json');
  }

  /**
   * Ensure the copilot relay script and hook config are in place. Called during
   * session launch — errors are logged but never thrown (non-fatal, same contract
   * as the Claude `HooksConfigService.ensureHooksConfig`).
   *
   * `_projectRootPath` is accepted for `HookConfigInstaller` parity but unused:
   * copilot's hook config is user-level, not per-project.
   */
  async ensureHooksConfig(_projectRootPath: string): Promise<void> {
    try {
      await mkdir(this.hooksDir, { recursive: true, mode: 0o700 });
      await this.materializeRelayScript();
      await this.writeHookConfig();
      logger.info('Copilot hooks config ensured successfully');
    } catch (error) {
      logger.error({ error }, 'Failed to ensure copilot hooks config (non-fatal)');
    }
  }

  /** Materialize the relay script atomically (tmp + rename), chmod +x. */
  private async materializeRelayScript(): Promise<void> {
    await this.atomicWrite(this.relayScriptPath, RELAY_SCRIPT_CONTENT, SCRIPT_FILE_MODE);
    // Ensure executable after rename (some filesystems may not preserve mode).
    await chmod(this.relayScriptPath, SCRIPT_FILE_MODE);
    logger.debug({ scriptPath: this.relayScriptPath }, 'Copilot relay script materialized');
  }

  /**
   * Write `~/.copilot/hooks/devchain.json` wholesale. The file is devchain-owned,
   * so it is overwritten (idempotent) rather than merged. The `bash` command passes
   * the PascalCase event name as `$1`; the relay path is quoted to survive spaces.
   */
  private async writeHookConfig(): Promise<void> {
    const quotedRelay = `"${this.relayScriptPath}"`;
    const config = {
      version: 1,
      hooks: {
        SessionStart: [
          { type: 'command', bash: `${quotedRelay} SessionStart`, timeoutSec: HOOK_TIMEOUT_SEC },
        ],
        Stop: [{ type: 'command', bash: `${quotedRelay} Stop`, timeoutSec: HOOK_TIMEOUT_SEC }],
      },
    };
    const output = JSON.stringify(config, null, 2) + '\n';
    await this.atomicWrite(this.configPath, output, CONFIG_FILE_MODE);
    logger.debug({ configPath: this.configPath }, 'Copilot hook config written');
  }

  /** Atomic write: write a uniquely-named temp file then rename into place. */
  private async atomicWrite(filePath: string, content: string, mode: number): Promise<void> {
    const tmpPath = `${filePath}.tmp.${process.pid}.${randomBytes(8).toString('hex')}`;
    try {
      await writeFile(tmpPath, content, { encoding: 'utf-8', mode });
      await rename(tmpPath, filePath);
    } catch (error) {
      try {
        await unlink(tmpPath);
      } catch {
        // Ignore cleanup errors
      }
      throw error;
    }
  }
}
